---
# Exercise for setting up a web server in an EC
- name: Exercise for setting up a web server in an EC   
  # Use the public IP if the VM is already created
  hosts: 35.90.242.248
  # For Ubuntu instances, the user will be `ubuntu`
  # For Amazon LInux 2 instance, the user will be `ec2-user`
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  roles:
   - setup