version: 2.1

jobs:
  env_details:
      docker:
        - image: cimg/base:2020.01
      steps:
      - checkout
      - run:
          name: "echo an env var that is part of our project"
          command: |
               echo $CIRCLE_WORKFLOW_ID
               echo $Owner_Name
        
  print_hello:
      docker:
        - image: cimg/node:17.2.0 # the primary container, where your job's commands are 
      steps:
        - run: echo "Hello Joshvi" > ~/output.txt # run the `echo` command and save file
        - persist_to_workspace:
           root: ~/
           paths:
             - output.txt
  print_world:
      docker:
        - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
      steps:
        - run: echo "world" # run the `echo` command
        - attach_workspace:
            at: ~/
        - run: cat ~/output.txt

workflows:
  joshvi-workflow:
    jobs:
      - env_details
      - print_hello:
          requires:
            - env_details
      - print_world:
          requires:
            - print_hello