version: 2.1

jobs:
  env_details:
      docker:
        - image: cimg/base:2020.01
      steps:
      - checkout
      - run:
          name: "echo an env var that is part of our project"
          command: |
               echo $MY_ENV_VAR
               echo $Owner_Name
        
  print_hello:
      docker:
        - image: cimg/node:17.2.0 # the primary container, where your job's commands are 
      steps:
        - run: echo "hello" # run the `echo` command
  print_world:
      docker:
        - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
      steps:
        - run: echo "world" # run the `echo` command

workflows:
  joshvi-workflow:
    jobs:
      - env_details
      - print_hello:
          requires:
            - env_details
      - print_world:
          requires:
            - print_hello