version: 2.1
commands:
  failure:
    steps:
      - run: 
          name: on error
          command: echo "Hello Error!"
          when: on_fail
  reusable:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}

jobs:
  env_details:
      docker:
        - image: cimg/base:2020.01
      steps:
      - checkout
      - reusable
      - run: echo $Owner_Name
        
  print_hello:
      docker:
        - image: cimg/node:17.2.0 # the primary container, where your job's commands are 
      steps:
        - checkout
        - reusable
        - run: echo "Hello Joshvi" > ~/output.txt # run the `echo` command and save file
        - persist_to_workspace:
           root: ~/
           paths:  
           - output.txt
        - run: exit 1
        - failure
  print_world:
      docker:
        - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
      steps:
        - checkout
        - run: echo "world" # run the `echo` command
        - attach_workspace:
            at: ~/
        - run: cat ~/output.txt
        - run: echo ~/output.txt

workflows:
  joshvi-workflow:
    jobs:
      - env_details
      - print_hello:
          requires:
            - env_details
      - print_world:
          requires:
            - print_hello