version: 2.1

jobs:
  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["c1:6f:0b:5a:a3:b0:29:db:a4:02:4c:62:39:05:1d:04"] # You can get this ID in the section where you registered the SSH Key
      - run:
          name: Install dependencies
          command: |
            # install the dependencies needed for your playbook
            apk add --update ansible 
      - run:
          name: Configure server
          command: |
            ansible-playbook -i inventory.txt main-remote.yml

#create_infrastructure: 
    #docker:
     # - image: amazon/aws-cli
   # steps:
    #  - checkout
     # - run:
     #     name: Create Cloudformation Stack
      #    command: |
        #    aws cloudformation deploy \
        #      --template-file template.yml \
         #     --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
         #     --region us-west-2
      # Fail the job intentionally to simulate an error.
      # Uncomment the line below if you want to fail the current step
      # - run: return 1
      #- destroy_environment
workflows:
  my_workflow:
    jobs:
      - configure_infrastructure